### SSH command
ssh -i autoops-key-fixed.pem ec2-user@54.186.48.127
ssh -i my-ec2-key ec2-user@54.218.116.222

ssh -i autoops-key-fixed.pem ec2-16-145-16-87.us-west-2.compute.amazonaws.com

ssh -i "C:\Users\frank\Desktop\3. Projects\13. Hackathons\3. AWS AI Agent Hackathon\AutoOps\backend\agent\my-ec2-key" ec2-user@ec2-44-245-205-90.us-west-2.compute.amazonaws.com

aws ec2 describe-images --image-ids ami-024e4b8b6ef78434a

aws ec2 associate-iam-instance-profile --instance-id i-0c4e1e261ac6df674 --iam-instance-profile Name=MyEC2Profile

aws ec2 associate-iam-instance-profile `
  --instance-id i-098f50e504fc8e8c1 `
  --iam-instance-profile Name=MyEC2Profile

---
aws ec2 describe-iam-instance-profile-associations `
  --filters Name=instance-id,Values=i-098f50e504fc8e8c1

aws sts get-caller-identity



### find instance ID's ssh key
aws ec2 describe-instances `
  --filters "Name=instance-state-name,Values=running" `
  --query "Reservations[*].Instances[*].[InstanceId,PublicDnsName]" `
  --output table

### change permissions on ec2 key I generated
chmod 600 my-ec2-key



### check what services are running
sudo lsof -i -P -n | grep python


### Security Group ID
sg-05b93c1804021efe6

### Authorize inbound traffic on port x 
aws ec2 authorize-security-group-ingress `
  --group-id sg-05b93c1804021efe6 `
  --protocol tcp `
  --port 3000 `
  --cidr 0.0.0.0/0

### View all running EC2 instances
aws ec2 describe-instances `
  --filters "Name=instance-state-name,Values=running" `
  --query "Reservations[*].Instances[*].{ID:InstanceId,Name:Tags[?Key=='Name']|[0].Value,State:State.Name,IP:PublicIpAddress}" `
  --output table

### Terminate all EC2 instances
aws ec2 terminate-instances `
  --instance-ids $(aws ec2 describe-instances `
  --filters "Name=instance-state-name,Values=running" `
  --query "Reservations[*].Instances[*].InstanceId" `
  --output text)


### launch EC2 instance
python .\launch_ec2.py app-inventory crash

### view service.log
cat service.log



aws ec2 import-key-pair `
  --key-name "my-ec2-key" `
  --public-key-material fileb://C:\Users\frank\Desktop\3. Projects\13. Hackathons\3. AWS AI Agent Hackathon\AutoOps\backend\agent\my-ec2-key.pub

aws ec2 import-key-pair `
  --key-name "my-ec2-key" `
  --public-key-material "fileb://C:\Users\frank\Desktop\3. Projects\13. Hackathons\3. AWS AI Agent Hackathon\AutoOps\backend\agent\my-ec2-key.pub"


aws ec2 describe-iam-instance-profile-associations `
  --filters Name=instance-id,Values=i-0271a7d6440f6184d
